/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import logic.Proceso;
import algoritmo.FCFS;
import algoritmo.Prioridad;
import algoritmo.RoundRobin;
import algoritmo.SJF;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;

public class VentanaPrincipalPrincipal extends javax.swing.JFrame {

    private List<Proceso> procesos;
    private DefaultListModel<String> listaProcesosModelo;
    private Map<Integer, JProgressBar> barrasDeProgreso;

    public VentanaPrincipalPrincipal() {
        procesos = new ArrayList<>();
          listaProcesosModelo = new DefaultListModel<>();
           barrasDeProgreso = new HashMap<>();
           
        setTitle("Simulador de Planificación de Procesos");
     
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        
        initComponents();// INIT COMPONENTES VA A LA GRAFFICA 
        agregarpane();

        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));//DYNAMIC
        // Inicializar la barra de progreso general
        barraProgresoGeneral.setStringPainted(true);//DYNAMIC
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoTiempoLlegada = new javax.swing.JTextField();
        campoTiempoRafaga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoNivelPrioridad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        barraProgresoGeneral = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOMBRE");

        jLabel2.setText("TIEMPO DE LLEGADA");

        jLabel3.setText("TIEMPO RAFAGA ");

        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("MEMORIA");

        campoNivelPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNivelPrioridadActionPerformed(evt);
            }
        });

        jLabel5.setText("PRIORIDAD");

        jToggleButton1.setText("Ejecutar FCFS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Ejecutar Round Robin");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Ejecutar SJF");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Ejecutar Prioridad");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        barraProgresoGeneral.setStringPainted(true);

        jPanel2.setPreferredSize(new java.awt.Dimension(176, 300));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jToggleButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jToggleButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoTiempoRafaga, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTiempoLlegada, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNivelPrioridad)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)
                                .addContainerGap())
                            .addComponent(barraProgresoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(campoTiempoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(campoTiempoRafaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(campoNivelPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(barraProgresoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregarProceso();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
ejecutarFCFS();   
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        ejecutarRoundRobin();

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
     ejecutarPrioridad();

    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void campoNivelPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNivelPrioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNivelPrioridadActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
      ejecutarSJF();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void agregarProceso() {
   int nombre = Integer.parseInt(campoNombre.getText());
        int tiempoLlegada = Integer.parseInt(campoTiempoLlegada.getText());
        int tiempoRafaga = Integer.parseInt(campoTiempoRafaga.getText());
        int prioridad = Integer.parseInt(campoNivelPrioridad.getText());

        Proceso proceso = new Proceso(nombre, tiempoLlegada, tiempoRafaga, prioridad);
        procesos.add(proceso);
        listaProcesosModelo.addElement(proceso.getNombre() + " - Llegada: " + tiempoLlegada + ", Ráfaga: " + tiempoRafaga + ", Prioridad: " + prioridad);

        campoNombre.setText("");
        campoTiempoLlegada.setText("");
        campoTiempoRafaga.setText("");
        campoNivelPrioridad.setText("");
    }

    public void agregarpane() {
        JList<String> listaProcesos = new JList<>(listaProcesosModelo);
        jScrollPane1.setViewportView(listaProcesos); // Aquí está la clave para el pane 
    }
    
     public void cargarBarrasDeProgreso() {
        jPanel2.removeAll();
        barrasDeProgreso.clear();
        for (Proceso proceso : procesos) {
            JProgressBar barraProgreso = new JProgressBar(0, proceso.getTiempoRafaga());
            barraProgreso.setStringPainted(true);
            barraProgreso.setString("" + proceso.getNombre());
            jPanel2.add(barraProgreso);
            jPanel2.revalidate();
            barrasDeProgreso.put(proceso.getNombre(), barraProgreso);
        }
    }
     
    public void actualizarBarraDeProgreso(Proceso proceso) {
        JProgressBar barraProgreso = barrasDeProgreso.get(proceso.getNombre());
        if (barraProgreso != null) {
            barraProgreso.setValue(proceso.getTiempoRafaga() - proceso.getTiempoRestante());
        }
    }
    
      private void simularEjecucion() {
        int tiempoTotalRafaga = procesos.stream().mapToInt(Proceso::getTiempoRafaga).sum();
        int tiempoActual = 0;

        for (Proceso proceso : procesos) {
            JProgressBar barraProgreso = barrasDeProgreso.get(proceso.getNombre());
            int rafaga = proceso.getTiempoRafaga();

            while (rafaga > 0) {
                try {
                    Thread.sleep(2000); // Simula la ejecución del proceso
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                rafaga--;
                tiempoActual++;
                barraProgreso.setValue(proceso.getTiempoRafaga() - rafaga);
                int progreso = (int) ((double) tiempoActual / tiempoTotalRafaga * 100);
                barraProgresoGeneral.setValue(progreso);
            }

            barraProgreso.setValue(proceso.getTiempoRafaga());
            barraProgresoGeneral.setValue((int) ((double) tiempoActual / tiempoTotalRafaga * 100));
        }

        JOptionPane.showMessageDialog(this, "Simulación completada.");
    }
    

    public void ejecutarRoundRobin() {
        cargarBarrasDeProgreso();
        new Thread(() -> {
            RoundRobin rr = new RoundRobin(2, this);
            rr.planificar(procesos); // Inicia el algoritmo Round Robin
        }).start();

    }

   private void ejecutarFCFS() {
        cargarBarrasDeProgreso();
        new Thread(() -> {
            FCFS algoritmoFCFS = new FCFS(this);
            algoritmoFCFS.planificar(procesos);
            simularEjecucion();
        }).start();
    }

    private void ejecutarPrioridad() {
        cargarBarrasDeProgreso();
        new Thread(() -> {
            Prioridad algoritmoPrioridad = new Prioridad(this);
            algoritmoPrioridad.planificar(procesos);
            simularEjecucion();
        }).start();
    }

    private void ejecutarSJF() {
        cargarBarrasDeProgreso();
        new Thread(() -> {
            SJF algoritmoSJF = new SJF(this);
            algoritmoSJF.planificar(procesos);
            simularEjecucion();
        }).start();
    }
 



    // agregar proceso al panel
//    private void agregarBarraDeProgreso(Proceso proceso) {
//        JProgressBar barraProgreso = new JProgressBar(0, proceso.getTiempoRafaga());
//        barraProgreso.setStringPainted(true);
//        barraProgreso.setString("" + proceso.getNombre());
//        jPanel2.add(barraProgreso);
//        jPanel2.revalidate(); // Refresca jPanel2 para mostrar nuevas barras
//    }
//
//    private void actualizarBarraDeProgreso(JProgressBar barraProgreso, int valor) {
//        barraProgreso.setValue(valor);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresoGeneral;
    private javax.swing.JTextField campoNivelPrioridad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTiempoLlegada;
    private javax.swing.JTextField campoTiempoRafaga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
